### ISSUE TITLE
Use USB Type C instead of micro B

### ISSUE THREAD

**Issue by SylveonDeko** [PhobGCC/PhobGCC-doc#13]
We've all seen the issues with micro usb and how it degrades really fast, so why not use usb c instead of micro? Is it a limitation of the raspi?

**Comment by CarVac** [comment]
1. This is the documentation repository, not the hardware v2 repository
2. We may do that for 2.0.6 (or whatever version ends up releasing after we fix teething issues) since we have switched to Elecrow as the main recommended board house.

We did micro in the first place because JLC has had a poor track record with USB-C.

**Comment by SylveonDeko** [comment]
Got it thanks!
